// Package wheelart draws the wheel's banner: the real wheel, unrolled into a strip.
//
// It exists for two reasons, and the first one is layout. An embed is only as wide as its
// widest content, so a card whose board is three short words renders narrow and one whose
// board is long renders wide, and the card visibly changes shape as the game goes on. An
// embed IMAGE sets the width, so a strip under every phase pins the card to one width on
// desktop and scales down on a phone.
//
// The second is that a strip can say something. There is one plain variant and one per wedge
// with that wedge lit and a pointer over it, so the banner under a spin shows where the wheel
// stopped. The wedges come from wheel.Wedges, so the picture cannot disagree with the wheel
// the engine spins.
//
// The images are generated by tools/wheelart and committed under assets/wheel, and served
// from the repository's raw URL: an image the card links to survives every edit, where an
// uploaded attachment would have to be re-sent with each repaint. A test compares the
// committed files with this package's output pixel for pixel.
package wheelart

import (
	"fmt"
	"image"
	"image/color"

	"github.com/6586x57890143/peregrine/internal/wheel"
)

// The strip's geometry, at twice the size Discord shows it, so it stays crisp on a dense
// screen. The pointer band sits above the wedges and is transparent unless a wedge is lit.
const (
	Width   = 800
	Height  = 48
	pointer = 10
	border  = 2
	frame   = 4
)

// Plain is the file name of the strip with nothing lit.
const Plain = "strip.png"

// Name is the file name of the strip with wedge i lit.
func Name(i int) string { return fmt.Sprintf("strip-%02d.png", i) }

var (
	ink       = color.NRGBA{0x1E, 0x1F, 0x22, 0xFF} // Discord's dark background
	edge      = color.NRGBA{0x11, 0x11, 0x14, 0xFF}
	highlight = color.NRGBA{0xFF, 0xFF, 0xFF, 0xFF}
)

// valueColour picks a gold wedge's colour by value, so equal values match wherever they sit.
var valueColour = map[int]color.NRGBA{
	300:  {0x9B, 0x59, 0xB6, 0xFF},
	400:  {0x1A, 0xBC, 0x9C, 0xFF},
	450:  {0x2E, 0xCC, 0x71, 0xFF},
	500:  {0x34, 0x98, 0xDB, 0xFF},
	550:  {0xE6, 0x7E, 0x22, 0xFF},
	600:  {0xE7, 0x4C, 0x3C, 0xFF},
	650:  {0xFF, 0x6F, 0xA9, 0xFF},
	700:  {0xF1, 0xC4, 0x0F, 0xFF},
	800:  {0x00, 0xBC, 0xD4, 0xFF},
	900:  {0x27, 0xAE, 0x60, 0xFF},
	2500: {0xFF, 0xD7, 0x00, 0xFF},
}

func wedgeColour(w wheel.Wedge) color.NRGBA {
	switch w.Kind {
	case wheel.Bankrupt:
		return color.NRGBA{0x0A, 0x0A, 0x0A, 0xFF}
	case wheel.LoseTurn:
		return color.NRGBA{0xF5, 0xF5, 0xF5, 0xFF}
	}
	if c, ok := valueColour[w.Value]; ok {
		return c
	}
	return color.NRGBA{0x95, 0xA5, 0xA6, 0xFF}
}

// Strip draws the wheel. lit is the wedge to light, or -1 for none. With a wedge lit, every
// other wedge is dimmed toward the background and a pointer marks the lit one, which is what
// makes the landing readable at a glance on a phone.
func Strip(lit int) image.Image {
	ws := wheel.Wedges()
	img := image.NewNRGBA(image.Rect(0, 0, Width, Height))
	for i, w := range ws {
		x0, x1 := i*Width/len(ws), (i+1)*Width/len(ws)
		c := wedgeColour(w)
		if lit >= 0 && i != lit {
			c = mix(c, ink, 0.6)
		}
		for x := x0; x < x1; x++ {
			for y := pointer; y < Height; y++ {
				px := c
				if x < x0+border/2 || x >= x1-border/2 || y < pointer+border || y >= Height-border {
					px = edge
				}
				img.SetNRGBA(x, y, px)
			}
		}
		// A triangle above the lit wedge, pointing down at it.
		if i == lit {
			mid := (x0 + x1) / 2
			for y := 0; y < pointer; y++ {
				half := (pointer - y) * (x1 - x0) / (2 * pointer)
				for x := mid - half; x <= mid+half; x++ {
					img.SetNRGBA(x, y, highlight)
				}
			}
			// A full white frame, because the two wedges people most need to see landed on,
			// BANKRUPT and LOSE A TURN, are black and white themselves.
			for x := x0; x < x1; x++ {
				for y := pointer; y < Height; y++ {
					if x < x0+frame || x >= x1-frame || y < pointer+frame || y >= Height-frame {
						img.SetNRGBA(x, y, highlight)
					}
				}
			}
		}
	}
	return img
}

// mix moves a toward b by t, keeping a's alpha.
func mix(a, b color.NRGBA, t float64) color.NRGBA {
	f := func(x, y uint8) uint8 { return uint8(float64(x)*(1-t) + float64(y)*t + 0.5) }
	return color.NRGBA{f(a.R, b.R), f(a.G, b.G), f(a.B, b.B), a.A}
}

// All is every file the strip comes in, by name.
func All() map[string]image.Image {
	out := map[string]image.Image{Plain: Strip(-1)}
	for i := range wheel.Wedges() {
		out[Name(i)] = Strip(i)
	}
	return out
}
